<?php


return [
    'secciones' => [
          1 => [
            'titulo' => 'Condiciones de Salud y Características Físicas',
            'descripcion' => 'En esta sección se recopila información relacionada con las condiciones generales de salud, antecedentes de molestias o lesiones y algunas características físicas. La información permitirá identificar posibles factores de interés para la prevención y seguimiento de riesgos relacionados con la Seguridad y Salud en el Trabajo.',
            'preguntas' => [
                1 => [
                    'texto'  => 'Peso (kg)',
                    'tipo'   => 'numero',
                    'obligatorio' => true,
                ],
                2 => [
                    'texto'  => 'Talla (Altura en cm)',
                    'tipo'   => 'numero',
                    'obligatorio' => true,
                ],
                3 => [
                    'texto'   => '¿Le han diagnosticado o sufre usted de alguna de las siguientes enfermedades?',
                    'tipo'    => 'checkbox_multiple',
                    'obligatorio' => true,
                    'opciones' => [
                        'Hipertensión',
                        'Diabetes',
                        'Enfermedad cardíaca',
                        'Enfermedades visuales (Miopía o Astigmatismo)',
                        'Gastritis o úlceras gástricas',
                        'Enfermedades músculo esqueléticas (artritis, osteoporosis, tendinitis, bursitis, etc.)',
                        'Obesidad',
                        'Estrés',
                        'Hipotiroidismo',
                        'ASMA',
                        'NINGUNA',
                    ],
                    'conOtro' => true,
                ],
                4 => [
                    'texto'  => '¿Cuál es su mano dominante?',
                    'tipo'   => 'mano_dominante',
                    'obligatorio' => true,
                ],
                5 => [
                    'texto'    => '¿Ha participado en actividades de salud realizadas por la empresa?',
                    'tipo'     => 'actividades_salud',
                    'obligatorio' => true,
                    'opciones'  => [
                        'Vacunación',
                        'Salud Oral',
                        'Exámenes de Laboratorio / otros',
                        'Exámenes Médicos (Ingreso y/o Periódicos)',
                        'Spa (Relajación)',
                        'Capacitaciones en Temas de Salud',
                        'Ninguna',
                    ],
                    'conOtro' => true,
                ],
                // Segmentos corporales (0–24)
                // Nota: se guardan como JSON { frecuencia, severidad }
                300 => ['texto' => '0. OJO',                      'tipo' => 'segmento_corporal', 'segmento' => 'OJO',                      'obligatorio' => true],
                301 => ['texto' => '1. CUELLO',                   'tipo' => 'segmento_corporal', 'segmento' => 'CUELLO',                   'obligatorio' => true],
                302 => ['texto' => '2. HOMBRO IZQUIERDO',         'tipo' => 'segmento_corporal', 'segmento' => 'HOMBRO IZQUIERDO',         'obligatorio' => true],
                303 => ['texto' => '3. HOMBRO DERECHO',           'tipo' => 'segmento_corporal', 'segmento' => 'HOMBRO DERECHO',           'obligatorio' => true],
                304 => ['texto' => '4. BRAZO IZQUIERDO',          'tipo' => 'segmento_corporal', 'segmento' => 'BRAZO IZQUIERDO',          'obligatorio' => true],
                305 => ['texto' => '5. BRAZO DERECHO',            'tipo' => 'segmento_corporal', 'segmento' => 'BRAZO DERECHO',            'obligatorio' => true],
                306 => ['texto' => '6. CODO IZQUIERDO',           'tipo' => 'segmento_corporal', 'segmento' => 'CODO IZQUIERDO',           'obligatorio' => true],
                307 => ['texto' => '7. CODO DERECHO',             'tipo' => 'segmento_corporal', 'segmento' => 'CODO DERECHO',             'obligatorio' => true],
                308 => ['texto' => '8. ANTEBRAZO DERECHO',        'tipo' => 'segmento_corporal', 'segmento' => 'ANTEBRAZO DERECHO',        'obligatorio' => true],
                309 => ['texto' => '9. ANTEBRAZO IZQUIERDO',      'tipo' => 'segmento_corporal', 'segmento' => 'ANTEBRAZO IZQUIERDO',      'obligatorio' => true],
                310 => ['texto' => '10. MUÑECA DERECHA',          'tipo' => 'segmento_corporal', 'segmento' => 'MUÑECA DERECHA',           'obligatorio' => true],
                311 => ['texto' => '11. MUÑECA IZQUIERDA',        'tipo' => 'segmento_corporal', 'segmento' => 'MUÑECA IZQUIERDA',         'obligatorio' => true],
                312 => ['texto' => '12. MANO IZQUIERDA',          'tipo' => 'segmento_corporal', 'segmento' => 'MANO IZQUIERDA',           'obligatorio' => true],
                313 => ['texto' => '13. MANO DERECHA',            'tipo' => 'segmento_corporal', 'segmento' => 'MANO DERECHA',             'obligatorio' => true],
                314 => ['texto' => '14. ZONA DORSAL',             'tipo' => 'segmento_corporal', 'segmento' => 'ZONA DORSAL',              'obligatorio' => true],
                315 => ['texto' => '15. ZONA LUMBAR',             'tipo' => 'segmento_corporal', 'segmento' => 'ZONA LUMBAR',              'obligatorio' => true],
                316 => ['texto' => '16. NALGAS / CADERAS',        'tipo' => 'segmento_corporal', 'segmento' => 'NALGAS / CADERAS',         'obligatorio' => true],
                317 => ['texto' => '17. MUSLO IZQUIERDO',         'tipo' => 'segmento_corporal', 'segmento' => 'MUSLO IZQUIERDO',          'obligatorio' => true],
                318 => ['texto' => '18. MUSLO DERECHO',           'tipo' => 'segmento_corporal', 'segmento' => 'MUSLO DERECHO',            'obligatorio' => true],
                319 => ['texto' => '19. RODILLA DERECHA',         'tipo' => 'segmento_corporal', 'segmento' => 'RODILLA DERECHA',          'obligatorio' => true],
                320 => ['texto' => '20. RODILLA IZQUIERDA',       'tipo' => 'segmento_corporal', 'segmento' => 'RODILLA IZQUIERDA',        'obligatorio' => true],
                321 => ['texto' => '21. PIERNA IZQUIERDA',        'tipo' => 'segmento_corporal', 'segmento' => 'PIERNA IZQUIERDA',         'obligatorio' => true],
                322 => ['texto' => '22. PIERNA DERECHA',          'tipo' => 'segmento_corporal', 'segmento' => 'PIERNA DERECHA',           'obligatorio' => true],
                323 => ['texto' => '23. PIE Y/O TOBILLO IZQUIERDO', 'tipo' => 'segmento_corporal', 'segmento' => 'PIE Y/O TOBILLO IZQUIERDO', 'obligatorio' => true],
                324 => ['texto' => '24. PIE Y/O TOBILLO DERECHO',  'tipo' => 'segmento_corporal', 'segmento' => 'PIE Y/O TOBILLO DERECHO',  'obligatorio' => true],
            ],
        ],

        2 => [
            'titulo' => 'Molestias experimentadas en los últimos 6 meses',
            'preguntas' => [
                7 => ['texto' => 'Dolor de cabeza', 'tipo' => 'si_no_detalle'],
                8 => ['texto' => 'Dolor de cuello, espalda y cintura', 'tipo' => 'si_no_detalle'],
                9 => ['texto' => 'Dolores musculares', 'tipo' => 'si_no_detalle'],
                10 => ['texto' => 'Dificultad para algún movimiento', 'tipo' => 'si_no_detalle'],
                11 => ['texto' => 'Tos frecuente', 'tipo' => 'si_no_detalle'],
                12 => ['texto' => 'Dificultad respiratoria', 'tipo' => 'si_no_detalle'],
                13 => ['texto' => 'Gastritis, úlcera', 'tipo' => 'si_no_detalle'],
                14 => ['texto' => 'Otras alteraciones del funcionamiento digestivo', 'tipo' => 'si_no_detalle'],
                15 => ['texto' => 'Alteraciones del sueño (insomnio, somnolencia)', 'tipo' => 'si_no_detalle'],
                16 => ['texto' => 'Dificultad para concentrarse', 'tipo' => 'si_no_detalle'],
                17 => ['texto' => 'Mal genio', 'tipo' => 'si_no_detalle'],
                18 => ['texto' => 'Nerviosismo', 'tipo' => 'si_no_detalle'],
                19 => ['texto' => 'Cansancio mental', 'tipo' => 'si_no_detalle'],
                20 => ['texto' => 'Palpitaciones', 'tipo' => 'si_no_detalle'],
                21 => ['texto' => 'Dolor en el pecho (angina)', 'tipo' => 'si_no_detalle'],
                22 => ['texto' => 'Cambios visuales', 'tipo' => 'si_no_detalle'],
                23 => ['texto' => 'Cansancio, fatiga, ardor o disconfort visual', 'tipo' => 'si_no_detalle'],
                24 => ['texto' => 'Pitos o ruidos continuos o intermitentes en los oídos', 'tipo' => 'si_no_detalle'],
                25 => ['texto' => 'Dificultad para oír', 'tipo' => 'si_no_detalle'],
                26 => ['texto' => 'Sensación permanente de cansancio', 'tipo' => 'si_no_detalle'],
                27 => ['texto' => 'Alteraciones en la piel', 'tipo' => 'si_no_detalle'],
                28 => ['texto' => 'Otras alteraciones no anotadas', 'tipo' => 'texto_libre'],
            ],
        ],

        3 => [
            'titulo' => 'Enfermedades diagnosticadas en brazos o piernas',
            'preguntas' => [
                29 => ['texto' => 'Enfermedades de los músculos, tendones y ligamentos (desgarros, tendinitis, bursitis, esguinces, torceduras)', 'tipo' => 'aplica_detalle'],
                30 => ['texto' => 'Enfermedades de los nervios (síndrome del túnel del carpo u otros)', 'tipo' => 'aplica_detalle'],
                31 => ['texto' => 'Fracturas', 'tipo' => 'aplica_detalle'],
                32 => ['texto' => 'Amputaciones en los brazos o piernas', 'tipo' => 'aplica_detalle'],
                33 => ['texto' => 'Acortamiento de una pierna', 'tipo' => 'aplica_detalle'],
                34 => ['texto' => 'Hernias (inguinal, abdominal)', 'tipo' => 'aplica_detalle'],
                35 => ['texto' => 'Várices en las piernas', 'tipo' => 'aplica_detalle'],
            ],
        ],

        4 => [
            'titulo' => 'Síntomas en manos, brazos, pies o piernas',
            'preguntas' => [
                36 => ['texto' => 'Adormecimiento u hormigueo', 'tipo' => 'aplica_detalle'],
                37 => ['texto' => 'Disminución de la fuerza', 'tipo' => 'aplica_detalle'],
                38 => ['texto' => 'Dolor o inflamación', 'tipo' => 'aplica_detalle'],
            ],
        ],

        5 => [
            'titulo' => 'Enfermedades o condiciones diagnosticadas',
            'preguntas' => [
                39 => ['texto' => 'Enfermedades del corazón', 'tipo' => 'aplica_detalle'],
                40 => ['texto' => 'Enfermedades de los pulmones (asma, enfisema, bronquitis)', 'tipo' => 'aplica_detalle'],
                41 => ['texto' => 'Diabetes (azúcar alta en la sangre)', 'tipo' => 'aplica_detalle'],
                42 => ['texto' => 'Enfermedades cerebrales (derrames, trombosis, epilepsia)', 'tipo' => 'aplica_detalle'],
                43 => ['texto' => 'Enfermedades de los huesos o articulaciones (artritis, gota, lupus, reumatismo, osteoporosis)', 'tipo' => 'aplica_detalle'],
                44 => ['texto' => 'Enfermedades de la columna vertebral (hernia de disco, compresión de raíces nerviosas, ciática, escoliosis o fractura)', 'tipo' => 'aplica_detalle'],
                45 => ['texto' => 'Enfermedades digestivas', 'tipo' => 'aplica_detalle'],
                46 => ['texto' => 'Enfermedades de la piel', 'tipo' => 'aplica_detalle'],
                47 => ['texto' => 'Alergias en piel o vías respiratorias', 'tipo' => 'aplica_detalle'],
                48 => ['texto' => 'Trastornos de audición', 'tipo' => 'aplica_detalle'],
                49 => ['texto' => 'Alteraciones visuales', 'tipo' => 'aplica_detalle'],
                50 => ['texto' => 'Hipertensión arterial o tensión alta', 'tipo' => 'aplica_detalle'],
                51 => ['texto' => 'Colesterol o triglicéridos elevados', 'tipo' => 'aplica_detalle'],
            ],
        ],

        6 => [
            'titulo' => 'Manifestaciones durante los últimos 6 meses',
            'preguntas' => [
                52 => ['texto' => 'Dolor en el pecho o palpitaciones', 'tipo' => 'si_no'],
                53 => ['texto' => 'Ahogo o asfixia al caminar', 'tipo' => 'si_no'],
                54 => ['texto' => 'Tos persistente por más de 1 mes', 'tipo' => 'si_no'],
                55 => ['texto' => 'Pérdida de la conciencia, desmayos o alteración del equilibrio', 'tipo' => 'si_no'],
            ],
        ],

        7 => [
            'titulo' => 'Hábitos o costumbres',
            'preguntas' => [
                56 => ['texto' => 'Fuma (no importa la cantidad ni la frecuencia)', 'tipo' => 'si_no'],
                57 => ['texto' => 'Toma bebidas alcohólicas semanal o quincenalmente (no importa la cantidad)', 'tipo' => 'si_no'],
                58 => ['texto' => 'Practica deportes de choque o de mano (baloncesto, voleibol, fútbol, tenis, squash, ping-pong, béisbol u otros) mínimo 2 veces al mes', 'tipo' => 'si_no'],
                59 => ['texto' => 'Realiza actividad física o deporte menos de 3 veces por semana', 'tipo' => 'si_no'],
            ],
        ],

        8 => [
            'titulo' => 'Condiciones del puesto de trabajo',
            'preguntas' => [
                60 => ['texto' => 'Conoce bien los riesgos a los que está sometido en su puesto de trabajo y las consecuencias para su salud', 'tipo' => 'si_no'],
                61 => ['texto' => 'Ha recibido capacitación sobre el manejo de los riesgos a los que está expuesto', 'tipo' => 'si_no'],
                62 => ['texto' => 'Considera que la iluminación de su puesto de trabajo es adecuada', 'tipo' => 'si_no'],
                63 => ['texto' => 'La temperatura de su sitio de trabajo le ocasiona molestias', 'tipo' => 'si_no'],
                64 => ['texto' => 'El ruido ambiental le permite mantener una conversación sin elevar el tono de voz', 'tipo' => 'si_no'],
                65 => ['texto' => 'En su sitio de trabajo hay presencia de polvo en el ambiente', 'tipo' => 'si_no'],
                66 => ['texto' => 'En el sitio de trabajo manipula o está en contacto con productos químicos', 'tipo' => 'si_no'],
                68 => ['texto' => 'Existe en su sitio de trabajo riesgo de incendio o explosión', 'tipo' => 'si_no'],
                69 => ['texto' => 'Considera que pisos, techos, paredes o escaleras presentan riesgo para su salud', 'tipo' => 'si_no'],
                70 => ['texto' => 'Existen cables sin entubar, empalmes defectuosos, tomas eléctricas sobrecargadas o transformadores defectuosos', 'tipo' => 'si_no'],
                71 => ['texto' => 'Los sitios de almacenamiento son suficientes, con espacio adecuado y productos bien apilados', 'tipo' => 'si_no'],
                72 => ['texto' => 'Las tareas que desarrolla le exigen realizar movimientos repetitivos', 'tipo' => 'si_no'],
                73 => ['texto' => 'Su labor genera riesgos de seguridad personal (sociales, naturales o públicos por desplazamiento)', 'tipo' => 'si_no'],
                74 => ['texto' => 'Permanece en la misma posición (sentado o de pie) más del 60% de la jornada', 'tipo' => 'si_no'],
                75 => ['texto' => 'La altura de la superficie de trabajo es adecuada a su estatura, silla y labor', 'tipo' => 'si_no'],
                76 => ['texto' => 'Tiene espacio suficiente para variar la posición de piernas y rodillas', 'tipo' => 'si_no'],
                77 => ['texto' => 'La silla es cómoda y permite ajustarla a su medida', 'tipo' => 'si_no'],
                78 => ['texto' => 'Dispone de espacio suficiente para trabajar con holgura', 'tipo' => 'si_no'],
                79 => ['texto' => 'Su trabajo le exige estar frente a la pantalla del computador más del 50% de la jornada', 'tipo' => 'si_no'],
                80 => ['texto' => 'Cree que la ubicación de su pantalla evita la presencia de reflejos', 'tipo' => 'si_no'],
                81 => ['texto' => 'El computador cuenta con filtro que favorezca el manejo de contrastes y disminuya la fatiga visual', 'tipo' => 'si_no'],
                82 => ['texto' => 'Cuenta con atril para ubicar documentos mientras trabaja en el computador', 'tipo' => 'si_no'],
                83 => ['texto' => 'Al finalizar la jornada, el cansancio que siente podría calificarse de "normal"', 'tipo' => 'si_no'],
                84 => ['texto' => 'Considera adecuada la distribución de horario, turnos, descansos, horas extra y pausas', 'tipo' => 'si_no'],
                85 => ['texto' => 'Considera adecuado el tiempo asignado a la tarea que realiza', 'tipo' => 'si_no'],
                86 => ['texto' => 'Puede abandonar el trabajo por unos minutos sin que lo sustituyan', 'tipo' => 'si_no'],
                87 => ['texto' => 'Puede variar el ritmo de trabajo sin perturbar la producción durante la jornada', 'tipo' => 'si_no'],
                88 => ['texto' => 'Las tareas que realiza le producen "sensación de peligrosidad"', 'tipo' => 'si_no'],
                89 => ['texto' => 'El trabajo le permite aplicar sus habilidades y conocimientos', 'tipo' => 'si_no'],
                90 => ['texto' => 'Considera que su trabajo es variado', 'tipo' => 'si_no'],
                91 => ['texto' => 'Su jefe le pide opinión sobre asuntos relacionados con su trabajo', 'tipo' => 'si_no'],
                92 => ['texto' => 'En su puesto de trabajo necesita utilizar elementos de protección personal', 'tipo' => 'si_no'],
                93 => ['texto' => 'Existen baños suficientes en número, con adecuado mantenimiento, dotación y aseo', 'tipo' => 'si_no'],
                94 => ['texto' => 'Cuenta con cocina, cafetería, comedor o sitio de descanso adecuadamente mantenidos, dotados y aseados', 'tipo' => 'si_no'],
                95 => ['texto' => 'La empresa cuenta con agua potable', 'tipo' => 'si_no'],
                96 => ['texto' => 'Existe buen manejo de basuras y desechos', 'tipo' => 'si_no'],
            ],
        ],

        9 => [
            'titulo' => 'Manifestaciones o comportamientos actuales',
               'sensible' => true,
            'preguntas' => [
                97 => ['texto' => 'Dificultades para dormirse (insomnio)', 'tipo' => 'si_no'],
                98 => ['texto' => 'Necesidad de estar solo y desinterés por las cosas', 'tipo' => 'si_no'],
                99 => ['texto' => 'Cansancio, aburrimiento o desgano', 'tipo' => 'si_no'],
                100 => ['texto' => 'Irritabilidad (mal genio), actitudes y pensamientos negativos', 'tipo' => 'si_no'],
                101 => ['texto' => 'Consumo de algún medicamento para los nervios o para dormir', 'tipo' => 'si_no'],
                102 => ['texto' => 'Siente que no puede manejar los problemas de su vida', 'tipo' => 'si_no'],
                103 => ['texto' => 'Dolor de cabeza, dificultad para concentrarse, trastornos intestinales, baja moral, descontento con el trabajo', 'tipo' => 'si_no'],
                104 => ['texto' => 'Tiene dificultad en la comunicación con sus compañeros y jefes', 'tipo' => 'si_no'],
                105 => ['texto' => 'Ha tenido problemas de salud a causa de su trabajo', 'tipo' => 'si_no'],
                106 => ['texto' => 'Tiene problemas con sus familiares', 'tipo' => 'si_no'],
            ],
        ],

        10 => [
            'titulo' => 'Capacitación',
            'preguntas' => [
                107 => ['texto' => 'Temas prioritarios de capacitación', 'tipo' => 'texto_libre'],
            ],
        ],

        11 => [
            'titulo' => 'Contacto de Emergencia',
            'preguntas' => [
                200 => [
                    'texto'       => 'EN CASO DE EMERGENCIA LLAMAR A:',
                    'tipo'        => 'checkbox_multiple',
                    'obligatorio' => true,
                    'opciones'    => [
                        'MADRE',
                        'PADRE',
                        'ESPOSA(O) / NOVIA(O)',
                        'HIJOS',
                        'HERMANO(A)',
                    ],
                    'conOtro' => true,
                ],
                201 => [
                    'texto'       => 'Número de Celular del Contacto de Emergencia (Ingrese un número de teléfono actualizado y disponible para contacto)',
                    'tipo'        => 'telefono',
                    'obligatorio' => true,
                ],
            ],
        ],
    ],
];
